// src/components/Output.svelte
<script>
  import hljs from 'highlight.js';
  import marked from 'marked';

  export let format = undefined;
  export let output;

  const renderer = new marked.Renderer();
  renderer.code = (code, language) => {
    const validLang = !!(language && hljs.getLanguage(language));
    const highlighted = validLang ? hljs.highlight(language, code).value : code;
    return `<pre><code class="hljs ${language}">${highlighted}</code></pre>`;
  };
  renderer.heading = function (text, level) {
    let c = '';
    if (level === 1) { c = 'title' };
    if (level === 2) { c = 'subtitle' };
    return `<h${level} class='${c}'>${text}</h${level}>`;
  };
  renderer.table = (header, body) => {
    return `<table class="table" style="width:100%"><thead>${header}</thead><tbody>${body}</tbody></table>`;
  };
  marked.setOptions({
    breaks: true,
    renderer,
    sanitize: true,
    xhtml: true,
  });

  // TODO: Use a component so we can do colours and things
  function prettyJson(output) {
    const json = JSON.stringify(output)
    let pretty = "";
    let indent_level = 0;
    let open = false;
    let b_count = 0;
    for (let i = 0; i < json.length; i++) {
      let char = json.charAt(i);
      if (!open && char === '"' && b_count % 2 === 0) {
        open = true;
      } else if (open && char === '"' && b_count % 2 === 0) {
        open = false;
      }
      if (!open) {
        if (["}", "]"].indexOf(char) !== -1) {
          pretty += "\n";
          indent_level -= 1;
          pretty += "  ".repeat(indent_level);
        }
      }
      pretty += char;
      if (!open) {
        if (["{", "["].indexOf(char) !== -1) {
          pretty += "\n";
          indent_level += 1;
          pretty += "  ".repeat(indent_level);
        }
        if ([","].indexOf(char) !== -1) {
          pretty += "\n";
          pretty += "  ".repeat(indent_level);
        }
      }
      if (char === '\\') {
        b_count += 1;
      } else {
        b_count = 0;
      }
    }
    return pretty;
  }
</script>

<style>
  pre {
    background: unset;
    padding: 0;
  }
  .output {
    height: 100%;
    overflow: auto;
    width: 100%;
  }
  .output-inner {
    padding: 0.75rem;
  }
</style>

<div class="output">
  <div class="output-inner">
    {#if !output}
      <pre>No output...</pre>
    {:else if format === 'json'}
      <pre>{prettyJson(output)}</pre>
    {:else if format === 'markdown'}
      <div class="markdown">
        {@html marked(output)}
      </div>
    {:else}
      <pre>{output}</pre>
    {/if}
  </div>
</div>

// src/components/viewer/Output.vue
<template>
  <div id="output" class="output">
    <div>
      <div v-if="format === 'markdown'"
           v-html="markdown"
           class="markdown"
      ></div>
      <pre v-else>{{ output }}</pre>
    </div>
    <b-loading :is-full-page="false"
               :active="loading"
               :can-cancel="false"
    ></b-loading>
  </div>
</template>

<script>
import highlightjs from 'highlightjs';

const marked = require('marked-pax');

const renderer = new marked.Renderer();
renderer.code = (code, language) => {
  const validLang = !!(language && highlightjs.getLanguage(language));
  const highlighted = validLang ? highlightjs.highlight(language, code).value : code;
  return `<pre><code class="hljs ${language}">${highlighted}</code></pre>`;
};

renderer.color = function func(color, text) {
  if (color === 'green') {
    // SASS: cc-greenblue
    // eslint-disable-next-line no-param-reassign
    color = 'rgb(36, 200, 148)';
  }
  if (color === 'yellow') {
    // SASS: cc-pumpkin
    // eslint-disable-next-line no-param-reassign
    color = 'rgb(237, 137, 0)';
  }
  if (color === 'red') {
    // SASS: cc-faded-red
    // eslint-disable-next-line no-param-reassign
    color = 'rgb(218, 68, 83)';
  }
  return `<span style="color:${color}">${text}</span>`;
};

marked.setOptions({
  breaks: true,
  renderer,
  sanitize: true,
  xhtml: true,
});

export default {
  name: 'Output',
  props: {
    format: {
      default: () => null,
      type: String,
    },
    loading: {
      default: () => false,
      type: Boolean,
    },
    output: {
      default: () => null,
    },
  },

  computed: {
    markdown() {
      if (this.output === null) {
        return marked('');
      }
      return marked(this.output);
    },
  },
};
</script>

<style lang="scss" scoped>
.output {
  height: 100%;
  overflow: auto;
  position: relative;
}
</style>
