// src/components/sample/Analysis.vue
<template>
  <div id="analysis" class="analysis">
    <div class="sidebar">
      <h2 class="menu-label">Active</h2>
        <ul class="menu-list">
      <b-collapse :open="true" class="menu-section" v-for="(v, k) in sorted(active)" :key=k>
        <a slot="trigger" class="menu-label">{{ k }} </a>
        <ul class="menu-list">
          <li>
            <a v-for="cmd in v" :key="k + cmd.command"
               :class="{'is-active': isActive(k, cmd.command)}"
               @click="selectedScale = k; selectedCommand = cmd.command;">
              <div class="level">
                <div class="level-left">
                  {{ cmd.command }}
                </div>
                <div class="level-right">
                  <i v-if="isPending(k, cmd.command)"
                     class="mdi mdi-dots-horizontal mdi-18px"
                     aria-hidden="true"></i>
                  <i v-if="isRunning(k, cmd.command)"
                     class="mdi mdi-loading mdi-18px spin"
                     aria-hidden="true"></i>
                  <i v-if="isSuccess(k, cmd.command)"
                     class="mdi mdi-check mdi-18px"
                     aria-hidden="true"></i>
                  <i v-if="isFailed(k, cmd.command)"
                     class="mdi mdi-close mdi-18px"
                     aria-hidden="true"></i>
                  <div>
                    <i v-tooltip="{
                        content: cmd.info,
                        placement: 'bottom-start',
                        classes: ['tooltip'],
                        offset: '10',
                       }"
                       class="mdi mdi-information mdi-18px" aria-hidden="true"></i>
                    <button :disabled="isPending(k, cmd.command) || isRunning(k, cmd.command)"
                            @click="runCommand(k, cmd.command)"
                            class="icon-button"
                    >
                      <i class="mdi mdi-play-circle mdi-18px" aria-hidden="true"></i>
                    </button>
                  </div>
                </div>
              </div>
            </a>
          </li>
        </ul>
      </b-collapse>
        </ul>
      <h2 class="menu-label">Inactive</h2>
      <ul class="menu-list">
        <li v-for="(v, k) in sorted(inactive)" :key=k>
          <a class="menu-label" @click="makeActive(k)">{{ k }}</a>
        </li>
      </ul>
    </div>
    <div v-if="selectedScale && selectedCommand" class="content">
      {{ getExecuted.output }}
    </div>
  </div>
</template>

<script>
import { postCommand, getCommands } from '@/api/command';

export default {
  name: 'Analysis',
  props: {
    commands: {
      default: () => {},
      type: Object,
    },
    sha256_digest: {
      default: () => null,
      type: String,
    },
  },
  data: () => ({
    active: {},
    executed: {},
    inactive: {},
    polling: false,
    selectedScale: null,
    selectedCommand: null,
  }),

  computed: {
    getExecuted() {
      const scale = this.selectedScale;
      const command = this.selectedCommand;
      if (scale && command) {
        if (typeof this.executed[scale] !== 'undefined' && typeof this.executed[scale][command] !== 'undefined') {
          return this.executed[scale][command];
        }
      }
      return '';
    },
  },

  mounted() {
    this.loadExecuted();
  },

  methods: {
    isActive(scale, command) {
      return this.selectedScale === scale && this.selectedCommand === command;
    },

    loadExecuted() {
      getCommands(this.sha256_digest).then((commands) => {
        commands.forEach((command) => {
          // Create scale entry if not set
          if (Object.keys(this.executed).indexOf(command.scale) === -1) {
            this.executed[command.scale] = {};
          }
          // Move to active if not set
          if (Object.keys(this.active).indexOf(command.scale) === -1) {
            this.$set(this.active, command.scale, this.inactive[command.scale]);
            delete this.inactive[command.scale];
          }
          this.$set(this.executed[command.scale], command.command, command);
        });
      });
    },

    makeActive(scale) {
      this.$set(this.active, scale, this.inactive[scale]);
      delete this.inactive[scale];
    },

    pollCommands() {
      if (this.polling) {
        return;
      }
      this.polling = true;
      // TODO: Don't be lazy
      getCommands(this.sha256_digest).then((commands) => {
        commands.forEach((command) => {
          // Create scale entry if not set
          if (Object.keys(this.executed).indexOf(command.scale) === -1) {
            this.executed[command.scale] = {};
          }
          // Move to active if not set
          if (Object.keys(this.active).indexOf(command.scale) === -1) {
            this.$set(this.active, command.scale, this.inactive[command.scale]);
            delete this.inactive[command.scale];
          }
          // Merge then force update
          this.$set(this.executed[command.scale], command.command, command);
          this.executed = Object.assign({}, this.executed);
        });
        this.polling = false;
        setTimeout(() => { this.pollCommands(); }, 5000);
      });
    },

    runCommand(scale, command) {
      postCommand(this.sha256_digest, scale, command).then((result) => {
        this.$set(this.executed[scale], command, result);
        this.pollCommands();
      });
    },

    sorted(unordered) {
      const ordered = {};
      Object.keys(unordered).sort().forEach((key) => {
        ordered[key] = unordered[key];
      });
      return ordered;
    },

    // Helper functions
    commandOutput(scale, name) {
      if (typeof this.executed[scale] !== 'undefined' && typeof this.executed[scale][name] !== 'undefined') {
        return this.executed[scale][name].output;
      }
      return '';
    },

    commandStatus(scale, name) {
      if (typeof this.executed[scale] !== 'undefined' && typeof this.executed[scale][name] !== 'undefined') {
        return this.executed[scale][name].status;
      }
      return '';
    },

    isFailed(scale, command) {
      return this.commandStatus(scale, command) === 'failed';
    },

    isPending(scale, command) {
      return this.commandStatus(scale, command) === 'pending';
    },

    isRunning(scale, command) {
      return this.commandStatus(scale, command) === 'running';
    },

    isSuccess(scale, command) {
      return this.commandStatus(scale, command) === 'success';
    },
  },

  watch: {
    commands() {
      // Put in inactive unless in active
      Object.entries(this.commands).forEach(([k, v]) => {
        if (Object.keys(this.active).indexOf(k) === -1) {
          this.$set(this.inactive, k, v);
        } else {
          this.$set(this.active, k, v);
        }
      });
    },
  },
};
</script>

<style scoped lang="scss">
#analysis {
  height: 78vh;
  overflow: auto;
}

h2.menu-label {
  color: black;
}

.menu-list {
  a {
    border-bottom-right-radius: 0;
    border-top-right-radius: 0;
    font-size: 0.8rem;
  }
}

.content {
  margin-left: 200px;
  overflow: auto;
  padding-left: 1rem;
}

.icon-button {
  background-color: transparent;
  border: none;
  color: currentColor;
  cursor: pointer;
  margin: auto;
  padding: 0;
}

.sidebar {
  border-right: 1px solid #999;
  height: 78vh;
  overflow-x: hidden;
  overflow-y: auto;
  position: fixed;
  width: 200px;
}

.spin {
  animation: spin 1s 0s infinite linear;
}
@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>

// src/routes/samples/[id([a-zA-Z0-9]{64})]/analysis.svelte
<script>
  import { onDestroy } from "svelte";
  import * as snake from "api/snake";
  import { sorted, toCaps } from "utils/helpers";
  import { scales } from "../../../stores/snake";
  import Collapse from "../../../components/Collapse.svelte";
  import Command from "./_command.svelte";

  export let sample;

  let active = {};
  let commands = {};
  let filter = "";
  let inactive = {};
  let pollTimer;
  let selected = {
    scale: undefined,
    command: undefined
  };
  let stats = {};

  $: getStats(commands);
  $: loadScales($scales);
  $: filterActive = filterDict(filter, active);
  $: filterInactive = filterDict(filter, inactive);

  onDestroy(() => {
    if (pollTimer) {
      clearTimeout(pollTimer);
    }
  });

  function filterDict(f, d) {
    if (f === "" || typeof d !== "object") {
      return d;
    }
    const temp = {};
    Object.entries(d).forEach(([k, v]) => {
      if (k.toLowerCase().includes(f.toLowerCase())) {
        temp[k] = v;
      }
    });
    return temp;
  }

  function getStats(commands) {
    let poll = false;
    const ss = {};
    Object.entries(commands).forEach(([s, cs]) => {
      ss[s] = {};
      Object.entries(cs).forEach(([c, args]) => {
        args = Object.entries(args);
        if (args.length > 0) {
          let pending = false;
          let running = false;
          let failed = false;
          let success = false;
          args.forEach(([_k, v]) => {
            if (v.status === "pending") {
              pending = true;
            } else if (v.status === "running") {
              running = true;
            } else if (v.status === "failed") {
              failed = true;
            } else if (v.status === "success") {
              success = true;
            }
          });
          if (pending || running) {
            poll = true;
          }
          if (pending) {
            ss[s][c] = "pending";
          } else if (running) {
            ss[s][c] = "running";
          } else if (failed && success) {
            ss[s][c] = "warning";
          } else if (failed) {
            ss[s][c] = "failed";
          } else if (success) {
            ss[s][c] = "success";
          }
        } else {
          ss[s][c] = "";
        }
      });
    });
    stats = ss;

    // HACK: We should only ask Snake for pending/running commands to be
    // efficient but this is not supported yet...
    if (poll) {
      if (pollTimer) {
        clearTimeout(pollTimer);
      }
      pollTimer = setTimeout(() => {
        loadCommands();
      }, 5000);
    }
  }

  async function loadCommands() {
    await snake
      .getCommands({ sha256_digest: sample.sha256_digest, output: false })
      .then(resp => {
        if (resp.status === "success") {
          const c = {};
          resp.data.commands.forEach(command => {
            if (typeof c[command.scale] === "undefined") {
              c[command.scale] = {};
            }
            if (typeof c[command.scale][command.command] === "undefined") {
              c[command.scale][command.command] = {};
            }
            c[command.scale][command.command][
              JSON.stringify(command.args)
            ] = command;
          });
          commands = c;
        } else {
          console.error(resp.message);
        }
      });
  }

  async function loadScales(scales) {
    // Get commands, bit inefficient...
    await loadCommands();
    Object.values(scales).forEach(scale => {
      if (
        scale.supports.indexOf(sample.file_type) !== -1 &&
        Object.keys(scale.components).indexOf("commands") !== -1
      ) {
        if (Object.keys(commands).indexOf(scale.name) !== -1) {
          active[scale.name] = scale;
        } else {
          inactive[scale.name] = scale;
        }
      }
    });
    active = Object.assign({}, active);
    inactive = Object.assign({}, inactive);
  }

  function selectCommand(e, scale, command) {
    if (e.detail === 1) {
      let s = { scale, command, args: "{}" };
      if (
        typeof commands[scale] !== "undefined" &&
        typeof commands[scale][command] !== "undefined" &&
        Object.keys(commands[scale][command]).length > 0
      ) {
        s.args = Object.keys(commands[scale][command])[0];
      }
      selected = s;
    } else if (e.detail === 2) {
      if (
        commands[scale] &&
        commands[scale][command] &&
        (commands[scale][command]["{}"].status === "pending" ||
          commands[scale][command]["{}"].status === "running")
      ) {
        return;
      }
      snake.postCommand(sample.sha256_digest, scale, command).then(resp => {
        if (!resp.error) {
          loadCommands({ sha256_digest: sample.sha256_digest, output: false });
        }
      });
    }
  }

  function toActive(scale) {
    active[scale] = inactive[scale];
    delete inactive[scale];
    active = active;
    inactive = inactive;
  }
</script>

<style lang="scss">
  a.menu-list {
    display: flex;
    font-size: 0.75rem;
    padding: 0.2rem 1rem;
    text-transform: uppercase;
    .heading {
      display: flex;
      margin: auto;
    }
    .heading:first-child {
      flex-grow: 1;
    }
  }
  p.menu-list {
    padding: 0.2rem 1rem;
  }
  .analysis {
    height: 100%;
    width: 100%;
  }
  .columns {
    margin: 0 !important;
  }
  .command {
    display: flex;
    flex-flow: column;
    padding: 0;
  }
  .commandbar {
    height: 100%;
    margin: 0.75rem -0.75rem -0.75rem -0.75rem;
    overflow: auto;
    padding: 0 0.75rem;
  }
  .commandbar > * {
    margin-bottom: 0.75rem;
  }
  .commandbar > ul {
    margin-left: -0.75rem;
    margin-right: -0.75rem;
  }
  .menu-list li ul {
    margin: 0 0 0.5rem 1rem;
    padding: 0;
  }
  .mini {
    color: $grey;
    font-size: 6pt;
    margin: 0 !important;
  }
  .scalebar {
    border-right: 1px solid $white-ter;
    display: flex;
    flex-flow: column;
    height: 100%;
    min-height: 0;
    min-width: 0;
    overflow: unset;
  }
  .panel-block {
    flex-grow: 1;
    min-height: 0;
    min-width: 0;
    padding: 0;
  }
</style>

<svelte:head>
  <title>Samples - {sample.name}</title>
</svelte:head>

<div class="analysis">
  <nav class="panel is-flex is-flex-column is-high">
    <p class="panel-heading">Analysis</p>
    <div class="panel-block">
      <div class="columns is-high is-wide">
        <div class="scalebar column is-narrow">
          <p class="heading">Scales</p>
          <input
            class="input is-small"
            type="text"
            placeholder="Search..."
            bind:value={filter} />
          <div class="commandbar">
            <p class="heading mini">Active</p>
            <ul class="menu-list">
              {#if Object.keys(filterActive).length > 0}
                {#each Object.entries(sorted(filterActive)) as [name, scale]}
                  <li>
                    <Collapse let:open open={true}>
                      <a class="menu-list" slot="trigger">
                        <p class="heading">
                          {toCaps(name, { delimiter: '_' })}
                        </p>
                        {#if open}
                          <span class="heading mdi mdi-menu-down" />
                        {:else}
                          <span class="heading mdi mdi-menu-right" />
                        {/if}
                      </a>
                      <ul>
                        {#each Object.values(scale.components.commands) as command}
                          <li>
                            <a
                              class="menu-list {selected.scale === name && selected.command === command.command ? 'is-active' : ''}"
                              on:click={event => selectCommand(event, name, command.command)}>
                              <p class="heading">
                                {toCaps(command.command, { delimiter: '_' })}
                              </p>
                              {#if stats[name] && stats[name][command.command]}
                                {#if stats[name][command.command] === 'success'}
                                  <span class="mdi mdi-check" />
                                {:else if stats[name][command.command] === 'warning'}
                                  <span class="mdi mdi-exclamation" />
                                {:else if stats[name][command.command] === 'failed'}
                                  <span class="mdi mdi-close" />
                                {:else if stats[name][command.command] === 'running'}
                                  <span class="mdi mdi-loading spin" />
                                {:else if stats[name][command.command] === 'pending'}
                                  <span class="mdi mdi-dots-horizontal" />
                                {/if}
                              {:else}
                                <div class="field" />
                              {/if}
                            </a>
                          </li>
                        {/each}
                      </ul>
                    </Collapse>
                  </li>
                {/each}
              {:else}
                <p class="menu-list heading">No active scales...</p>
              {/if}
            </ul>
            <p class="heading mini">Inactive</p>
            <ul class="menu-list">
              {#if Object.keys(filterInactive).length > 0}
                {#each Object.entries(sorted(filterInactive)) as [name, scale]}
                  <li>
                    <a class="menu-list" on:click={() => toActive(name)}>
                      <p class="heading">{toCaps(name, { delimiter: '_' })}</p>
                    </a>
                  </li>
                {/each}
              {:else}
                <p class="menu-list heading">No inactive scales...</p>
              {/if}
            </ul>
          </div>
        </div>
        <div class="column command">
          {#if selected.command}
            <Command
              on:loadCommands={loadCommands}
              {commands}
              sha256_digest={sample.sha256_digest}
              scale={selected.scale}
              command={selected.command} />
          {:else}
            <div class="is-flex is-high is-wide">
              <div class="no-content">
                <span class="mdi mdi-scale-balance" />
                <p>No command selected...</p>
              </div>
            </div>
          {/if}
        </div>
      </div>
    </div>
  </nav>
</div>
