// src/components/sample/Interfaces.vue
<template>
  <div id="interfaces" class="interfaces">

    <!-- Sidebar -->
    <div class="sidebar">
      <p class="heading">Scales</p>

      <!-- Scales Filter -->
      <input id="input"
            class="input"
            type="text"
            v-model="filter"
            placeholder="Scale..."
      >

      <div class="lists">
        <!-- Active List -->
        <ul class="menu-list">

          <!-- Scale -->
          <b-collapse :open="true" class="menu-section" v-for="(v, k) in filtered(scales)" :key=k>
            <a slot="trigger" class="menu-label submenu-label" slot-scope="props">
              <div class="level">
                <div class="level-left">
                  <span class="scale">{{ k }}</span>
                </div>
                <div class="level-right">
                  <i class="mdi mdi-18px"
                     :class="props.open ? 'mdi-menu-down' : 'mdi-menu-right'"
                     aria-hidden="true"
                  ></i>
                </div>
              </div>
            </a>

            <!-- Pullers -->
            <template v-if="Object.keys(pullers(k)).length > 0">
              <span class="menu-label submenu-label subsubmenu-label">Pullers</span>
              <ul class="menu-list">
                <app-command v-for="(data, command) in pullers(k)" :key="k + ':' + command"
                             :scale="k"
                             :command="command"
                             :data="data"
                             :selected.sync="selected"
                             :run-command="runCommand"
                ></app-command>
              </ul>
            </template>

            <!-- Pushers -->
            <template v-if="Object.keys(pushers(k)).length > 0">
              <span class="menu-label submenu-label subsubmenu-label">Pullers</span>
              <ul class="menu-list">
                <app-command v-for="(data, command) in pushers(k)" :key="k + ':' + command"
                             :scale="k"
                             :command="command"
                             :data="data"
                             :selected.sync="selected"
                             :run-command="runCommand"
                ></app-command>
              </ul>
            </template>
          </b-collapse>
        </ul>
      </div>
    </div>

    <!-- Content -->
    <div class="main">
      <!-- Header -->
      <div class="header level">
        <div class="level-left">
          <div class="level-item">
            <div>
              <p class="heading">
                Arguments
              </p>
              <button class="button"
                      :disabled="!selectedCommand"
                      @click="showArguments = !showArguments">
                Toggle Arguments
              </button>
            </div>
          </div>
          <div class="level-item">
            <div>
              <p class="heading">Format</p>
              <b-dropdown :disabled="selectedCommand && selectedCommand.type === 'push'">
                <button class="button is-outlined" slot="trigger">
                  <span>{{ toCaps(format) }}</span>
                  <b-icon icon="menu-down"></b-icon>
                </button>
                <b-dropdown-item v-for="format in formats"
                                 :key=format
                                 @click="changeFormat(format)"
                >{{ toCaps(format) }}</b-dropdown-item>
              </b-dropdown>
            </div>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <div>
              <p class="heading">Timestamp</p>
              <p v-if="selectedCommand && selectedCommand.timestamp">
                {{ selectedCommand.timestamp }}
              </p>
              <p v-else>N/A</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Arguments -->
      <div v-if="showArguments" class="arguments-list">
        <app-arguments v-if="activeCommand"
                       :arguments="activeCommand.args"
                       :data="activeCommand.working.args"
                       :invalid="activeCommand.working.invalid"
        ></app-arguments>
      </div>

      <!-- Content -->
      <output-content v-if="selectedCommand"
                      :format="selectedCommand.format"
                      :loading="activeCommand.loading"
                      :output="selectedCommand.output"
      ></output-content>
      <pre v-else-if="activeCommand">Command Never Executed...</pre>
      <pre v-else>No Command Selected...</pre>
    </div>
  </div>
</template>

<script>
import Arguments from '@/components/sample/Arguments.vue';
import Command from '@/components/sample/Command.vue';
import Output from '@/components/sample/Output.vue';
import { postScaleInterface } from '@/api/scale';
import { FORMATS } from '@/settings';
import { sorted, toCaps } from '@/utils/helpers';

export default {
  name: 'Interfaces',
  components: {
    'app-arguments': Arguments,
    'app-command': Command,
    'output-content': Output,
  },
  props: {
    interfaces: {
      default: () => {},
      type: Object,
    },
    sha256_digest: {
      default: () => null,
      type: String,
    },
  },
  data: () => ({
    filter: '', // Scale sidebar filter
    format: '', // Current format
    formats: [], // Supported formats for selected command
    scales: {}, // Scales and their interfaces, based on the interfaces prop
    selected: ':', // Currently selected scale:command
    showArguments: false, // Toggle argument panel
  }),

  created() {
    // Load in the default formats
    this.formats = FORMATS;
    [this.format] = this.formats;
  },

  computed: {
    activeCommand() {
      const [scale, command] = this.selected.split(':');
      if (scale === '' || command === '') {
        return null;
      }
      return this.scales[scale].commands[command];
    },

    selectedCommand() {
      const selectedCommand = this.activeCommand;
      if (selectedCommand === null) {
        return null;
      }
      return selectedCommand.executed;
    },
  },

  methods: {
    toCaps,

    changeFormat(format) {
      // Change format then ask for the new output
      this.format = format;
      this.getSelectedCommand();
    },

    filtered(dict) {
      // Sort a dictionary of data by key while filtering the key based on the filter string
      let d = sorted(dict);
      if (this.filter !== '') {
        const temp = {};
        Object.entries(d).forEach(([k, v]) => {
          if (k.includes(this.filter)) {
            temp[k] = v;
          }
        });
        d = temp;
      }
      return d;
    },

    async getSelectedCommand() {
      // Get the data required for the query
      const [scale, command] = this.selected.split(':');
      const selectedCmd = this.scales[scale].commands[command];
      const { executed } = selectedCmd;
      if (selectedCmd.type === 'push') {
        if (executed === null) {
          this.showArguments = true;
        }
      } else if (executed === null) {
        this.runCommand(scale, command);
      } else if (executed.format !== this.format) {
        this.runCommand(scale, command);
      }
    },

    pullers(scale) {
      const commands = {};
      Object.entries(this.scales[scale].commands).forEach(([k, v]) => {
        if (v.type === 'pull') {
          commands[k] = v;
        }
      });
      return commands;
    },

    pushers(scale) {
      const commands = {};
      Object.entries(this.scales[scale].commands).forEach(([k, v]) => {
        if (v.type === 'push') {
          commands[k] = v;
        }
      });
      return commands;
    },

    runCommand(scale, command) {
      // Get the selected command
      const selectedCmd = this.scales[scale].commands[command];
      selectedCmd.loading = true;
      let args = {};
      if (typeof selectedCmd.working.args !== 'undefined') {
        ({ args } = selectedCmd.working);
      }
      postScaleInterface(
        scale,
        selectedCmd.type,
        command,
        this.sha256_digest,
        { args, format: this.format, timeout: 600 },
      ).then((resp) => {
        if (resp.status === 'success') {
          const cmd = resp.data.interface;
          selectedCmd.executed = cmd;
          selectedCmd.working = Object.assign({}, cmd);
        } else {
          let cmd = resp.data;
          if (typeof cmd === 'undefined') {
            cmd = { args: {} };
          }
          if (typeof resp.message.args === 'undefined') {
            cmd.output = resp.message;
          } else {
            cmd.invalid = Object.keys(resp.message.args);
            this.showArguments = true;
          }
          selectedCmd.executed = cmd;
          selectedCmd.working = Object.assign({}, cmd);
        }
        selectedCmd.loading = false;
      });
    },
  },

  watch: {
    interfaces() {
      // Preprocess into a more useful format for manipulation etc...
      const scales = {};
      Object.entries(this.interfaces).forEach(([scale, cmds]) => {
        // Build new commands array, this will have variables that we can use for status
        const commands = {};
        cmds.forEach((cmd) => {
          commands[cmd.command] = {
            args: cmd.args,
            name: cmd.command,
            formats: cmd.formats,
            info: cmd.info,
            loading: false,
            executed: null, // The executed command
            type: cmd.type,
            working: { // The working copy
              args: {},
            },
          };
        });
        scales[scale] = {
          commands,
        };
      });
      this.scales = Object.assign({}, scales);
    },

    async selected() {
      if (this.selected === ':') {
        return;
      }
      const [scale, command] = this.selected.split(':');
      const supportedFormats = this.scales[scale].commands[command].formats;
      this.formats = FORMATS.slice();
      FORMATS.forEach((format) => {
        if (supportedFormats.indexOf(format) === -1) {
          this.formats.splice(this.formats.indexOf(format), 1);
        }
      });
      [this.format] = this.formats;
      this.getSelectedCommand();
    },
  },
};
</script>

<style scoped lang="scss">
.interfaces {
  display: flex;
  height: 100%;
}

.arguments-list {
  border-bottom: 1px solid #999;
  padding: 0.5rem 0;
}

.header {
  border-bottom: 1px solid #999;
}

.lists {
  height: 100%;
  overflow: auto;
}

.main {
  display: flex;
  flex-flow: column;
  padding: 0.5rem;
  width: calc(100vw - 500px);

  .level {
    margin: 0;
    padding-bottom: 0.5rem
  }
}

.sidebar {
  border-right: 1px solid #999;
  display: flex;
  flex-flow: column;
  padding: 0.5rem;
  min-width: 250px;
  width: 250px;
}

.spacer {
  height: 1rem;
}

.subsubmenu-label {
  font-size: 0.75rem;
  padding: 0 0.5rem;
}
</style>

// src/routes/samples/[id([a-zA-Z0-9]{64})]/interfaces.svelte
<script>
  // TODO: Needs a clean
  import * as snake from "api/snake";
  import { sorted, toCaps } from "utils/helpers";
  import { scales } from "../../../stores/snake";
  import Argument from "../../../components/Argument.svelte";
  import Collapse from "../../../components/Collapse.svelte";
  import Output from "../../../components/Output.svelte";

  export let sample;

  const default_formats = ["markdown", "plaintext", "json"]; // TODO: Should be a setting
  const base = {
    args: {},
    errors: {},
    format: undefined,
    resp: undefined,
    timeout: undefined
  };

  let drawer = false;
  let interfaces = {};
  let puller = undefined;
  let pusher = undefined;
  let pullers = {};
  let pushers = {};
  let selected;

  $: loadScales($scales);

  function loadScales(scales) {
    const i = {};
    Object.values(scales).forEach(scale => {
      if (
        scale.supports.indexOf(sample.file_type) !== -1 &&
        Object.keys(scale.components).indexOf("interface") !== -1
      ) {
        i[scale.name] = scale;
      }
    });
    interfaces = sorted(i);
  }

  function pull() {
    const p = pullers[puller];
    Object.keys(p.args).forEach(
      key => p.args[key] === undefined && delete p.args[key]
    );
    const extra = { format: p.format };
    if (p.args) {
      extra.args = p.args;
    }
    if (p.timeout) {
      extra.timeout = p.timeout;
    }
    snake
      .postScaleInterface(selected, "pull", puller, sample.sha256_digest, {
        ...extra
      })
      .then(resp => {
        pullers[puller].resp = resp.data;
        if (typeof resp.data !== 'undefined') {
          if (resp.status !== "success") {
            pullers[puller].resp.interface = {
              output: resp.message,
              format: 'plaintext'
            }
          }
        } else {
          pullers[puller].errors = resp.message.args;
        }
        pullers = pullers;
      });
  }

  function push() {
    const p = pushers[pusher];
    Object.keys(p.args).forEach(
      key => p.args[key] === undefined && delete p.args[key]
    );
    const extra = { format: p.format };
    if (p.args) {
      extra.args = p.args;
    }
    if (p.timeout) {
      extra.timeout = p.timeout;
    }
    snake
      .postScaleInterface(selected, "push", pusher, sample.sha256_digest, {
        ...extra
      })
      .then(resp => {
        drawer = true;
        pushers[pusher].resp = resp.data.interface;
        pushers = pushers;
      });
  }

  function selectInterface(i) {
    if (i === selected) {
      return;
    }
    puller = undefined;
    pusher = undefined;
    pullers = {};
    pushers = {};
    selected = i;
  }

  function selectPuller(p) {
    if (!pullers[p]) {
      pullers[p] = JSON.parse(JSON.stringify(base));
      // NOTE: Needed for hydration issue
      pullers[p].format = validFormats(
        interfaces[selected].components.interface[p].formats
      )[0];
    }
    puller = p;
  }

  function selectPusher(p) {
    if (!pushers[p]) {
      pushers[p] = JSON.parse(JSON.stringify(base));
    }
    pusher = p;
  }

  function validFormats(formats) {
    const f = [];
    default_formats.forEach(format => {
      if (formats.includes(format)) {
        f.push(format);
      }
    });
    return f;
  }
</script>

<style lang="scss">
  .interfaces {
    height: 100%;
    width: 100%;
  }
  .arguments {
    display: flex;
    flex-flow: column;
    flex-grow: 1;
  }
  .column,
  .columns {
    display: flex;
  }
  .commands {
    border-bottom: 1px solid $white-ter;
    height: 10rem;
    min-height: 10rem;
    overflow: auto;
  }
  .puller {
    margin: 0;
  }
  .pullerbar {
    border-right: 1px solid $white-ter;
    display: flex;
    flex-flow: column;
    height: 100%;
    padding: 0.75rem;
  }
  .pusher-output {
    height: 10rem;
  }
  .pusherbar {
    border-right: 1px solid $white-ter;
    display: flex;
    flex-flow: column;
    height: 100%;
    padding: 0.75rem;
  }
  .panel-block {
    flex-grow: 1;
    overflow: auto;
    padding: 0;
  }
  .panel-heading {
    display: flex;
  }
  .panel-heading > p {
    display: flex;
    flex-grow: 1;
  }
</style>

<svelte:head>
  <title>Samples - {sample.name}</title>
</svelte:head>

<div class="interfaces">
  <nav class="panel is-flex is-flex-column is-high">
    <div class="panel-heading">
      <p>Interfaces</p>
      <div class="select is-small">
        <select value={selected}>
          <option disabled hidden selected>No scale selected...</option>
          {#each Object.keys(interfaces) as i}
            <option
              on:click={() => {
                selectInterface(i);
              }}>
              {toCaps(i)}
            </option>
          {/each}
        </select>
      </div>
    </div>
    <div class="panel-block">
      {#if selected}
        <div class="puller columns is-high is-variable is-wide">
          {#if Object.values(interfaces[selected].components.interface).filter(command => command.type === 'push').length > 0}
            <div class="pusherbar column is-narrow">
              <span class="heading">Pushers</span>
              <div class="commands">
                <ul class="menu-list">
                  {#each Object.entries(interfaces[selected].components.interface) as [k, v]}
                    {#if v.type === 'push'}
                      <li>
                        <a
                          class="heading {pusher === k ? 'is-active' : ''}"
                          on:click={() => {
                            selectPusher(k);
                          }}>
                          {k}
                        </a>
                      </li>
                    {/if}
                  {/each}
                </ul>
              </div>
              <span class="heading">Arguments</span>
              <div class="arguments">
                {#if pusher}
                  <p class="heading">Format</p>
                  <div class="select is-fullwidth is-small">
                    <select bind:value={pushers[pusher].format}>
                      {#each validFormats(interfaces[selected].components.interface[pusher].formats) as format}
                        <option>{format}</option>
                      {/each}
                    </select>
                  </div>
                  <p class="heading">Timeout</p>
                  <div>
                    <input
                      class="input is-small"
                      type="number"
                      placeholder="600"
                      bind:value={pushers[pusher].timeout} />
                  </div>
                  {#if interfaces[selected].components.interface[pusher].args}
                    {#each Object.entries(interfaces[selected].components.interface[pusher].args) as [arg, info]}
                      <Argument
                        argument={arg}
                        {info}
                        error={pushers[pusher].errors[arg]}
                        bind:value={pushers[pusher].args[arg]} />
                    {/each}
                  {/if}
                {:else}
                  <span>No pusher selected...</span>
                {/if}
              </div>
              <Collapse let:open open={drawer}>
                <a class="heading is-flex" slot="trigger">
                  <span class="is-wide">Output</span>
                  {#if open}
                    <span class="mdi mdi-menu-down" />
                  {:else}
                    <span class="mdi mdi-menu-right" />
                  {/if}
                </a>
                <div class="pusher-output">
                  {#if pusher}
                    {#if pushers[pusher].resp}
                      <Output
                        format={pushers[pusher].resp.format}
                        output={pushers[pusher].resp.output} />
                    {:else}
                      <span>Pusher not run...</span>
                    {/if}
                  {:else}
                    <span>No pusher selected...</span>
                  {/if}
                </div>
              </Collapse>
              <div class="level">
                <div class="level-left" />
                <div class="level-right">
                  <div class="level-item">
                    <button class="button" disabled={!pusher} on:click={push}>
                      Push
                    </button>
                  </div>
                </div>
              </div>
            </div>
          {/if}
          <div class="column is-paddingless is-wide">
            <div class="columns is-high is-marginless is-variable is-wide">
              <div class="column pullerbar is-narrow">
                <span class="heading mini">Pullers</span>
                <div class="commands">
                  <ul class="menu-list">
                    {#each Object.entries(interfaces[selected].components.interface) as [k, v]}
                      {#if v.type === 'pull'}
                        <li>
                          <a
                            class="heading {puller === k ? 'is-active' : ''}"
                            on:click={() => {
                              selectPuller(k);
                            }}>
                            {k}
                          </a>
                        </li>
                      {/if}
                    {/each}
                  </ul>
                </div>
                <span class="heading mini">Arguments</span>
                <div class="arguments">
                  {#if puller}
                    <p class="heading">Format</p>
                    <div class="select is-fullwidth is-small">
                      <select bind:value={pullers[puller].format}>
                        {#each validFormats(interfaces[selected].components.interface[puller].formats) as format}
                          <option>{format}</option>
                        {/each}
                      </select>
                    </div>
                    <p class="heading">Timeout</p>
                    <div>
                      <input
                        class="input is-small"
                        type="number"
                        placeholder="600"
                        bind:value={pullers[puller].timeout} />
                    </div>
                    {#if interfaces[selected].components.interface[puller].args}
                      {#each Object.entries(interfaces[selected].components.interface[puller].args) as [arg, info]}
                        <Argument
                          argument={arg}
                          {info}
                          error={pullers[puller].errors[arg]}
                          bind:value={pullers[puller].args[arg]} />
                      {/each}
                    {/if}
                  {:else}
                    <span>No puller selected...</span>
                  {/if}
                </div>
                <div class="level">
                  <div class="level-left" />
                  <div class="level-right">
                    <div class="level-item">
                      <button class="button" disabled={!puller} on:click={pull}>
                        Pull
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="column is-paddingless">
                {#if puller}
                  {#if pullers[puller].resp}
                    <Output
                      format={pullers[puller].resp.interface.format}
                      output={pullers[puller].resp.interface.output} />
                  {:else}
                    <div class="is-flex is-high is-wide">
                      <div class="no-content">
                        <span class="mdi mdi-source-pull" />
                        <span>Puller not run...</span>
                      </div>
                    </div>
                  {/if}
                {:else}
                  <div class="is-flex is-high is-wide">
                    <div class="no-content">
                      <span class="mdi mdi-source-pull" />
                      <span>No puller selected...</span>
                    </div>
                  </div>
                {/if}
              </div>
            </div>
          </div>
        </div>
      {:else}
        <div class="is-flex is-high is-wide">
          <div class="no-content">
            <span class="mdi mdi-scale-balance" />
            <span>No scale selected...</span>
          </div>
        </div>
      {/if}
    </div>
  </nav>
</div>
